# Generated by Django 4.1.2 on 2022-10-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customers",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="promotion",
            new_name="promotions",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="orders",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="uu",
        ),
        migrations.AlterField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount",
            field=models.FloatField(),
        ),
    ]
