# Generated by Django 4.1.2 on 2022-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=15),
        ),
    ]
